# GitHub Pages configuration for Lustify AI - Updated
title: "Lustify AI - Create Your Own AI Influencer"
description: "Professional AI Avatar and Content Generation Platform - Creator Core AI Replica"
url: "https://kingivthe1st.github.io"
baseurl: "/lustify"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - node_modules/
  - src/
  - package.json
  - package-lock.json
  - Dockerfile
  - docker-compose.yml
  - README.md
  - .env.example
  - .github/
  - scripts/

# Include files
include:
  - index.html